local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-p>', builtin.find_files, {})
vim.keymap.set('n', '<leader>rg', builtin.live_grep)
vim.keymap.set('n', '<leader>p', builtin.current_buffer_fuzzy_find)
vim.keymap.set('n', '<leader>fm', builtin.marks)
vim.keymap.set('n', '<leader>?', builtin.keymaps)
